
package vista;

import controlador.CtrlCategory;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Category;

public class JIFCategorys extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCategory
     */
    public JIFCategorys() {
        initComponents();
        this.setSize(new Dimension(500,350));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("04b", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripcion de la categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 180, -1));

        Save.setBackground(new java.awt.Color(204, 255, 204));
        Save.setFont(new java.awt.Font("04b", 1, 12)); // NOI18N
        Save.setText("Save");
        Save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cafe.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       
        Category category = new Category();
        CtrlCategory controlCategory = new CtrlCategory ();
        
        category.setDescripcion(txtDescripcion.getText().trim());
        category.setEstado(1);
        
        if(txtDescripcion.getText() .isEmpty()){
               JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else{
            
            if(!controlCategory.existCategory(txtDescripcion.getText().trim())){
                   category.setDescripcion(txtDescripcion.getText().trim());
            category.setEstado(1);          
            if(controlCategory.guardar(category)){
                   JOptionPane.showMessageDialog(null, "Registro Guardado");
            }else{
              JOptionPane.showMessageDialog(null, "Error al Guardar");
            }
            }else{
               JOptionPane.showMessageDialog(null, "Ya esxite la categoria");
            }   
        }
      txtDescripcion.setText("");
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
